services:
  demo-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-demo-db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "demo"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
